### ISSUE TITLE
Add option for specifying the output path

### ISSUE THREAD

**Issue by lightyrs** [makaroni4/sandi_meter#61]
Ideally, I can specify where the sandi_meter directory will be outputted.  For me, this is (in a Rails app), `spec/reports/sandi_meter`.

Thanks for a great gem!

**Comment by Mehonoshin** [comment]
Feel free to make PR :)

**Comment by dkarter** [comment]
i'm on it (I have it done - just need to work on some testing and push)

**Comment by dkarter** [comment]
see https://github.com/makaroni4/sandi_meter/pull/62

**Comment by dkarter** [comment]
PR #62 merged in - can be closed now!

**Comment by makaroni4** [comment]
@dkarter sure :rocket: 

I will release a new version of sandi_meter next week, with or without all PR merged.
